version: '3.3'

services: 

  gallery-db:

    build: ./database/
    volumes: [data:/backups/]
    ports: [3306:3306]
    restart: always
    env_file: [./config/db.env]  

  gallery-back: 
  
    depends_on: [gallery-db]
    build: ./backend/
    ports: [3333:3333]
    restart: always

  gallery-front: 

    depends_on: [gallery-back]
    build: ./frontend/
    ports: [3000:3000]
    restart: always
      
volumes: 

  data: {}


